### PR TITLE
Daniel hernandez

### PR DESCRIPTION
**Pull request by danielhcg**
I really hope I did this right.

### CODE REVIEW

**Review by cjardin — CHANGES_REQUESTED** [review]
Has conflicts from last pull.. Please update.

**Comment by danielhcg** [comment]
2nd attempt for a successful pull request. I upadated from the last pull. Ran it on my machine and everything worked.

**Comment by danielhcg** [comment]
i really hope i did this one correct.

**Review by cjardin — APPROVED** [review]

**Review by cjardin — CHANGES_REQUESTED** [review]
Please don't commit  dot_actor.py .. That file doesn't need to be changed.. Further, your commit will not work as submitted.. You need to add griddy and griddyKiller to the g4

**Comment by danielhcg** [comment]
I made sure not to commit dot_actor.py and I added griddy and griddykiller to the g4 file.

**Review by cjardin — CHANGES_REQUESTED** [review]
g4 has changed and you have a conflict .. please update.

**Review by cjardin — APPROVED** [review]
I will do the merge

**Comment by danielhcg** [comment]
Thanks professor. Also, does my contribution count as a B?

**Comment by cjardin** [comment]
Too much todo to grade right now.

**Pull request merged**
